development: &global_settings
  database: intralist_development
  host: 127.0.0.1
  port: 27017

production:
  database: intralist_production
  username: rubyspider
  password: rubyspider27017
  <<: *global_settings